auth_mechanisms {
  oauthbearer = yes
  xoauth2 = yes
  plain = no
  login = no
}

ssl = no
auth_allow_cleartext = yes
submission_relay_host = localhost

oauth2 {
  introspection_url = http://sso:8082/auth/realms/test/protocol/openid-connect/userinfo 
  introspection_mode = auth
  username_attribute = preferred_username
}
