services:
    koha:
        image: koha/koha-testing:${KOHA_IMAGE:-main}
        depends_on:
            - db
            - memcached
        cap_add:
            - ALL
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        environment:
            COVERAGE: ${COVERAGE:-}
            CPAN: ${CPAN:-no}
            EXTRA_CPAN: ${EXTRA_CPAN:-}
            EXTRA_APT: ${EXTRA_APT:-}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
            KOHA_CI_INCREMENTAL_RUN_REPO_URL: ${KOHA_CI_INCREMENTAL_RUN_REPO_URL:-}
            KOHA_CI_INCREMENTAL_RUNS: ${KOHA_CI_INCREMENTAL_RUNS:-}
            KOHA_CI_INCREMENTAL_RUNS_REPORT: ${KOHA_CI_INCREMENTAL_RUNS_REPORT:-}
            KOHA_CI_INCREMENTAL_RUNS_TOKEN: ${KOHA_CI_INCREMENTAL_RUNS_TOKEN:-}
            KOHA_ELASTICSEARCH: ${KOHA_ELASTICSEARCH:-no}
            KOHA_PROVE_CPUS: ${KOHA_PROVE_CPUS:-}
            SKIP_CYPRESS_CHOWN: ${SKIP_CYPRESS_CHOWN:-no}
            SKIP_L10N: ${SKIP_L10N:-no}
            KOHA_IMAGE: ${KOHA_IMAGE:-main}
            KOHA_MARC_FLAVOUR: ${KOHA_MARC_FLAVOUR:-marc21}
            MANA_URL: ${MANA_URL}
            USE_EXISTING_DB: ${USE_EXISTING_DB:-yes}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            kohanet:
                aliases:
                    - "${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}"
    memcached:
        image: ${MEMCACHED_IMAGE:-memcached}
        command: memcached -m 64m
        networks:
            - kohanet

networks:
    kohanet:
        enable_ipv4: ${ENABLE_IPV4:-true}
        enable_ipv6: ${ENABLE_IPV6:-false}
